# Generated by Django 4.2.30 on 2026-05-28 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTrailEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Record Created"),
                            ("UPDATE", "Record Updated"),
                            ("APPROVE", "Record Approved"),
                            ("UNAPPROVE", "Record Unapproved"),
                            ("FLAG_CREATE", "Flag Created"),
                            ("FLAG_DISMISS", "Flag Dismissed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("field_name", models.CharField(blank=True, max_length=100, null=True)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("justification", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Audit Trail Event",
                "verbose_name_plural": "Audit Trail Events",
                "db_table": "audit_trail_events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ClientCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audit_lock_date",
                    models.DateField(
                        blank=True,
                        help_text="Date after which approved records cannot be unapproved",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Company",
                "verbose_name_plural": "Client Companies",
                "db_table": "client_companies",
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP_IDOC", "SAP IDoc"),
                            ("SAP_CSV", "SAP CSV"),
                            ("GREEN_BUTTON", "Green Button XML"),
                            ("CONCUR_API", "Concur API"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="Parser-specific configuration (e.g., column mappings, custom conversions)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sources",
                        to="ingestion.clientcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Source",
                "verbose_name_plural": "Data Sources",
                "db_table": "data_sources",
            },
        ),
        migrations.CreateModel(
            name="NormalizedRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("activity_date", models.DateField()),
                (
                    "emission_scope",
                    models.CharField(
                        choices=[
                            ("SCOPE_1", "Scope 1: Direct Emissions"),
                            ("SCOPE_2", "Scope 2: Purchased Electricity"),
                            ("SCOPE_3", "Scope 3: Value Chain"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        help_text="e.g., fuel_combustion, electricity_consumption, air_travel",
                        max_length=100,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "unit",
                    models.CharField(help_text="Standardized unit", max_length=50),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "original_quantity",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                ("original_unit", models.CharField(max_length=50)),
                (
                    "conversion_factor",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("FLAGGED", "Flagged for Review"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_records",
                        to="ingestion.clientcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Normalized Record",
                "verbose_name_plural": "Normalized Records",
                "db_table": "normalized_records",
            },
        ),
        migrations.CreateModel(
            name="ValidationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("NUMERIC_RANGE", "Numeric Range"),
                            ("REQUIRED_FIELD", "Required Field"),
                            ("DATE_RANGE", "Date Range"),
                            ("ENUM_VALUES", "Enumerated Values"),
                            ("CUSTOM", "Custom Rule"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Name of the field to validate (e.g., 'quantity', 'activity_date')",
                        max_length=100,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        help_text="Rule configuration (e.g., {'min': 0, 'max': 1000} or {'allowed_values': ['A', 'B']})"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        help_text="Error message to display when validation fails"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this rule is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_rules",
                        to="ingestion.clientcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation Rule",
                "verbose_name_plural": "Validation Rules",
                "db_table": "validation_rules",
            },
        ),
        migrations.CreateModel(
            name="SuspiciousFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("OUTLIER", "Statistical Outlier"),
                            ("MISSING_FIELD", "Missing Required Field"),
                            ("INVALID_DATE", "Invalid Date Range"),
                            ("CONVERSION_FAILURE", "Unit Conversion Failed"),
                            ("DUPLICATE", "Duplicate Record"),
                            ("VALIDATION_RULE", "Validation Rule Violation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DISMISSED", "Dismissed"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("dismissal_justification", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dismissed_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="ingestion.normalizedrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suspicious Flag",
                "verbose_name_plural": "Suspicious Flags",
                "db_table": "suspicious_flags",
            },
        ),
        migrations.CreateModel(
            name="RawDataRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_data", models.JSONField(help_text="Unparsed input data")),
                ("ingestion_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "parsing_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("parsing_error", models.TextField(blank=True, null=True)),
                (
                    "client_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_records",
                        to="ingestion.clientcompany",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_records",
                        to="ingestion.datasource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw Data Record",
                "verbose_name_plural": "Raw Data Records",
                "db_table": "raw_data_records",
            },
        ),
        migrations.AddField(
            model_name="normalizedrecord",
            name="raw_record",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="normalized_record",
                to="ingestion.rawdatarecord",
            ),
        ),
        migrations.AddIndex(
            model_name="clientcompany",
            index=models.Index(fields=["name"], name="client_comp_name_084189_idx"),
        ),
        migrations.AddField(
            model_name="audittrailevent",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_events",
                to="ingestion.normalizedrecord",
            ),
        ),
        migrations.AddField(
            model_name="audittrailevent",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="validationrule",
            index=models.Index(
                fields=["client_company", "is_active"],
                name="validation__client__b9a8e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="suspiciousflag",
            index=models.Index(
                fields=["record", "status"], name="suspicious__record__e9ff30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawdatarecord",
            index=models.Index(
                fields=["client_company", "ingestion_timestamp"],
                name="raw_data_re_client__444d0e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawdatarecord",
            index=models.Index(
                fields=["data_source", "parsing_status"],
                name="raw_data_re_data_so_a777fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedrecord",
            index=models.Index(
                fields=["client_company", "activity_date"],
                name="normalized__client__737250_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedrecord",
            index=models.Index(
                fields=["client_company", "emission_scope"],
                name="normalized__client__e582c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedrecord",
            index=models.Index(
                fields=["client_company", "approval_status"],
                name="normalized__client__a7c32f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["client_company", "source_type"],
                name="data_source_client__873f87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audittrailevent",
            index=models.Index(
                fields=["record", "timestamp"], name="audit_trail_record__09f218_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrailevent",
            index=models.Index(
                fields=["user", "timestamp"], name="audit_trail_user_id_e72578_idx"
            ),
        ),
    ]
